milestone2
1v4n4/bookstore pull request #2
Opened 2021-08-18 17:10 UTC by 1v4n4

In this milestone, I created components , containers, actions, reducer, and store. The app can display the default set of books. It is deployed on Heroku (link in readme).

2021-08-18 20:09 UTC, taiwo2 requested changes
# STATUS: CHANGES REQUIRED ♻️ 
@1v4n4 well done on this milestone and I commend your effort in trying to met the requirements, however, few changes are required
### highlight 
Git flow 👍🏻 
project structure 👍🏻 

### To Improve
#### src/index.js
kindly changed `bookstore.js` to `App.js` as recommended by the project requirement
### bookstore` component
 kindly change `bookstore.js` component to `App.js` component

### BooksList component
* [ ] it connects to Redux store, using the `connect()` function or [Redux hooks](https://react-redux.js.org/api/hooks), and fetches books from the state [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/BooksList/ConnetToReduxHooks.png) from [pathwright](https://microverse.pathwright.com/library/react-redux-v10/188148/path/step/107676536/)
* [ ] it uses `mapStateToProps` to fetch books from the `store`
* [ ] kindly remove `console.log  from your code

`index.js` reducer 

- it combines app specific reducers, uses `combineReducer`and kindly remove `console.log` in your file
kindly find my inline comments

#### once specific changes are made request for another review

2021-08-18 20:17 UTC, taiwo2 requested changes

2021-08-18 20:17 UTC, taiwo2 commented on src/index.js
> +      <Bookstore />
change the component file name to App.js

2021-08-18 20:17 UTC, taiwo2 commented on src/containers/BookList.js
> +  console.log(list);
remove console.log

2021-08-18 20:17 UTC, taiwo2 commented on src/reducers/index.js
> +console.log('store state from reducers', store.getState());
remove the console and use  `combinedReducers` to  combines app specific reducers

2021-08-18 20:20 UTC, taiwo2 requested changes

2021-08-18 20:20 UTC, taiwo2 commented on src/containers/BookList.js
> +  const list = store.getState();
its connect redux to store using `connect()` function  and it uses `mapStateToProps` to fetch books from the `store`

2021-08-19 08:50 UTC, bellom approved these changes
## Hi @1v4n4  :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best**

2021-08-19 08:56 UTC, merged